let family1=["Hindu Marriage Act, 1955","Special Marriage Act, 1954","Muslim Personal Law (Shariat) Application Act, 1937","Dowry Prohibition Act, 1961","Protection of Women from Domestic Violence Act, 2005"]
let family2=["Governs marriage, divorce, and related issues for Hindus, Buddhists, Sikhs, and Jains."," Provides a secular framework for marriages (often used for interfaith unions) and covers registration, divorce, and related matters"," Applies aspects of Sharia law to personal matters (marriage, divorce, inheritance) for Indian Muslims."," Prohibits the giving or taking of dowry and aims to curb dowry-related violence."," Provides protection and legal remedies to women facing domestic abuse and violence."]
let family3=[["•Contravening age requirements","The HMA sets minimum ages of 21 for grooms and 18 for brides. Violating these age requirements is punishable by imprisonment of up to 15 days or a fine of up to Rs 1,000, or both.","•Marriage between Sapindas","A marriage between two people who are related by Sapinda is void. The punishment for this includes imprisonment of up to one month and a fine of up to Rs 1,000, or both.","•Contravening other conditions","•Violating other conditions specified in the HMA can result in:","Rigorous imprisonment of up to two years or a fine of up to Rs 100,000, or both","Simple imprisonment of up to one month or a fine of up to Rs 1,000, or both"],["•Imprisonment: Up to one year in prison","•Fine: Up to Rs. 500","•Offenses","Knowingly solemnizing a marriage without publishing a notice as required by Section 5","Solemnizing a marriage within 30 days of publishing the notice","•	Solemnizing a marriage in contravention of any provision of the Act"],["•If the violation involves fraud or forgery, relevant IPC sections (e.g., Section 420 for cheating, Section 468 for forgery) could be invoked.","• In case of any fraudulent transfer or dealing of property contrary to the Act, civil suits or other legal remedies might be pursued"],["•Offense and Punishment (Section 3):","If any person demands dowry, directly or indirectly, as a condition for marriage or during the marriage process, they are liable to imprisonment for a term that can extend up to 6 months and a fine of up to ₹10,000.","•Giving or Taking Dowry (Section 4):","If any person gives, takes, or abets the giving or taking of dowry, they can be punished with imprisonment of up to 5 years and a fine which may extend to ₹15,000 or the value of the dowry, whichever is higher","•Dowry Death (Section 304B of IPC):","If a woman dies within 7 years of marriage due to burns or bodily injury, or under suspicious circumstances, and it is found that she was subjected to cruelty or harassment related to dowry, it is considered a dowry death. In such cases, the punishment can be imprisonment for life or death."],["• Non-compliance with Protection Orders:",": If a person (usually the respondent) violates a protection order or fails to comply with the directions provided by the court under the PWDVA, the person may be punished under section 31 of the Act. The punishment can include:Imprisonment for up to 1 year, or A fine, or both.","•Non-compliance with Residence Orders:"," If a respondent fails to abide by the residence order, which mandates the respondent to provide the woman with a place to stay or not to enter her place of residence, they could face penalties","•Breach of Interim Orders:","If any interim order passed by the Magistrate under the PWDVA is violated, there are provisions for contempt of court."]]
let busin1=["Information Technology Act, 2000 (IT Act, 2000)","The Indian Penal Code (IPC), 1860","The Personal Data Protection Bill, 2019","The National Cyber Security Policy, 2013","5.	The Information Technology Rules, 2011"]
let busin2=["The IT Act is the primary legislation governing electronic commerce, cybercrimes, and digital signatures. It provides legal recognition for electronic records and digital signatures and defines offenses related to hacking, cyberterrorism, identity theft, and data privacy.","The IPC contains provisions relevant to cybercrimes, including fraud, defamation, and trespassing, which apply in the context of online activities. Sections 420, 463, and 66 of the IPC deal with cyber fraud, forgery, and related offenses.","This bill seeks to regulate the collection, processing, and storage of personal data, with an emphasis on consent, accountability, and transparency. It is India's attempt to align with global data protection standards like the GDPR and establish a legal framework for personal data privacy.","Although not a law, this policy provides a framework to protect India's cyberspace. It aims to build secure computing environments, prevent cybercrimes, and promote research and development in cybersecurity. The policy focuses on capacity building, critical information infrastructure protection, and awareness.","These rules, issued under the IT Act, mandate that companies follow reasonable security practices and protect sensitive personal data. They outline the requirements for data storage, processing, and transfer, and provide guidelines for data breaches, including the need for prompt reporting."]
let farm1=["Essential Commodities Act, 1955","Protection of Plant Varieties and Farmers’ Rights Act, 2001","Seeds Act, 1966","Agricultural Produce Grading and Marking Act, 1937","National Dairy Development Board Act"]
let farm2=["Empowers the government to regulate the production, supply, and distribution of essential commodities (including key agricultural products) to prevent hoarding and price manipulation.","Regulate the marketing of agricultural produce and ensure that farmers get fair prices by creating regulated market yards","Provides intellectual property protection for new plant varieties while safeguarding farmers’ rights to save, use, exchange, and sell seeds.","Regulates the quality and sale of seeds to ensure that farmers have access to certified, high-quality planting material","Establishes standards for grading and marking agricultural produce to improve market transparency and quality control"," Provides the framework for the development of the dairy industry, ensuring fair practices and support for dairy farmers in a key agricultural sector"]
let women1=["Protection of Women from Domestic Violence Act, 2005","Sexual Harassment of Women at Workplace (Prevention, Prohibition and Redressal) Act,2013","Indecent Representation of Women (Prevention) Act, 1986","National Commission for Women Act, 1990","The Pre-Conception and Pre-Natal Diagnostic Techniques (Prohibition of Sex Selection) Act, 1994"]
let women2=[" Provides civil remedies and protection for women facing physical, emotional, or economic abuse at home."," Mandates internal complaint mechanisms and prevention strategies in workplaces to protect women from sexual harassment."," Prohibits indecent representation of women through advertisements or other media, curbing objectification and exploitation."," Establishes a statutory body to advise the government on policies and measures for safeguarding women’s rights and interests."," Prohibits sex-selective practices and ensures that the use of diagnostic techniques does not reinforce gender discrimination."]
let envim1=["Environment (Protection) Act, 1986","Air (Prevention and Control of Pollution) Act, 1981","Wildlife Protection Act, 1972","Forest Conservation Act, 1980","Biological Diversity Act, 2002"]
let envim2=["The umbrella legislation empowering the government to take measures for environmental protection and control pollution","Regulates air quality by controlling the emission of pollutants from industrial and vehicular sources","Provides for the protection of wild animals, birds, and plants, and establishes national parks and sanctuaries","Regulates the diversion of forest land for non-forest purposes, safeguarding forests and biodiversity.","Aims to conserve biological diversity and ensure equitable sharing of benefits arising from the use of genetic resources"]
let emplo1=["Industrial Disputes Act, 1947","Factories Act, 1948","Payment of Bonus Act, 1965","Maternity Benefit Act, 1961 (as amended)","Employees’ Provident Funds and Miscellaneous Provisions Act, 1952"]
let emplo2=["Provides mechanisms for dispute resolution between employers and employees,including retrenchment and layoffs."," Regulates working conditions, safety, health, and welfare in factories."," Mandates a minimum wage for different sectors and regions, protecting workers from exploitation"," Requires payment of bonuses to employees based on profits and productivity in establishments with 20 or more workers."," Grants maternity leave and related benefits to female employees, now extended and modernized in recent amendments"," Establishes a compulsory savings scheme for retirement benefits, ensuring long-term social security."]

let optnsimg=document.querySelector("#optns");
let mainimg2=document.querySelector(".imgs")
let optns=document.querySelector("#col");
let h3=document.querySelector(".mainch3")
let p=document.querySelector(".maincp")
let law=document.querySelectorAll(".lws");
let vilns=document.querySelector(".mainv");
let vilnsp=document.querySelector(".voilenp")
let lawyer=document.querySelector(".lawyimg")
optnsimg.addEventListener("click",()=>{optns.style="display:block";
    let mainimg1=document.querySelector("#mainimgs");
    mainimg1.style.width="970px";
    mainimg1.style.height="430px";
    mainimg2.style="display: inline-block;position: absolute; top: 28%; left: 19%;  width: auto; height: 50px; "
})
law.forEach((lws) =>{
    lws.addEventListener("click",()=>{
        lawyer.style="visibility: hidden;";
    for(let i=0;i<10;i++){
        if(family1[i]===lws.innerText){
            h3.innerText=family1[i];
            p.innerText=family2[i];
            vilns.style="visibility: visible;";
            vilnsp.innerHTML="";
                for(let j=0;j<family3[i].length;j++){
                vilnsp.innerHTML= vilnsp.innerHTML +`<p>${family3[i][j]}</p>`;}
                }
                }}
)} )
            
            
